home:
    path:       /{lang}/home
    controller: homeController::indexAction
    defaults:
        lang:   es   

login:
    path:       /{lang}/login
    controller: loginController::indexAction
    defaults:
        lang:   es   


panties:
    path:       /{lang}/panties
    controller: pantiesController::indexAction
    defaults:
        lang:   es   

legal:
    path:       /{lang}/legal
    controller: pantiesController::indexAction
    defaults:
        lang:   es   

swimsuit:
    path:       /{lang}/swimsuit
    controller: swimsuitController::indexAction
    defaults:
        lang:   es   

bras:
    path:       /{lang}/bras
    controller: brasController::indexAction
    defaults:
        lang:   es   

contacto:
    path:       /{lang}/contacto
    controller: contactoController::indexAction
    defaults:
        lang:   es   
    